// // File generated by FlutterFire CLI.
// // ignore_for_file: type=lint
// import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
// import 'package:flutter/foundation.dart'
//     show defaultTargetPlatform, kIsWeb, TargetPlatform;
//
// /// Default [FirebaseOptions] for use with your Firebase apps.
// ///
// /// Example:
// /// ```dart
// /// import 'firebase_options.dart';
// /// // ...
// /// await Firebase.initializeApp(
// ///   options: DefaultFirebaseOptions.currentPlatform,
// /// );
// /// ```
// class DefaultFirebaseOptions {
//   static FirebaseOptions get currentPlatform {
//     if (kIsWeb) {
//       throw UnsupportedError(
//         'DefaultFirebaseOptions have not been configured for web - '
//         'you can reconfigure this by running the FlutterFire CLI again.',
//       );
//     }
//     switch (defaultTargetPlatform) {
//       case TargetPlatform.android:
//         return android;
//       case TargetPlatform.iOS:
//         return ios;
//       case TargetPlatform.macOS:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for macos - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.windows:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for windows - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       case TargetPlatform.linux:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions have not been configured for linux - '
//           'you can reconfigure this by running the FlutterFire CLI again.',
//         );
//       default:
//         throw UnsupportedError(
//           'DefaultFirebaseOptions are not supported for this platform.',
//         );
//     }
//   }
//
//   static const FirebaseOptions android = FirebaseOptions(
//     apiKey: "AIzaSyCvVN4TF-QciA6Tlc-mG1fT5apa7r6-VWQ",
//     appId: "1:248340309733:android:120615bbcf0c7d636d960c",
//     messagingSenderId: "248340309733",
//     projectId: "link-application-6f0b6",
//     storageBucket: "link-application-6f0b6.firebasestorage.app",
//   );
//
//   static const FirebaseOptions ios = FirebaseOptions(
//     apiKey: "AIzaSyC2GmkiCtEtfpqki8tqwTJmSSP6hW8lHek",
//     appId: "1:248340309733:ios:e98f724e28e236a26d960c",
//     messagingSenderId: "248340309733",
//     projectId: "link-application-6f0b6",
//     storageBucket: "link-application-6f0b6.firebasestorage.app",
//     iosBundleId: "com.tarrance.eztrack_rental",
//   );
// }
